dotnet/admin-dashboard/Admin.Web/Controllers/CustomersController.cs
using System.Linq;
using System.Threading.Tasks;
using Admin.Web.Models;
using Admin.Web.ViewModels.Customers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Admin.Web.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private readonly AdminContext _context;

        public CustomersController(AdminContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var customers = await _context.Customers.ToArrayAsync();
            return View(new IndexViewModel
            {
                Customers = customers
            });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateViewModel viewModel)
        {
            _context.Add(new Customer
            {
                FirstName = viewModel.FirstName,
                LastName = viewModel.LastName,
                Address = new Address
                {
                    AddressLine1 = viewModel.AddressLine1,
                    City = viewModel.City,
                    Country = viewModel.Country,
                    State = viewModel.State,
                    ZipCode = viewModel.ZipCode
                }
            });
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var viewModel = await _context.Customers
                .Select(c => new EditViewModel
                {
                    Id = c.Id,
                    FirstName = c.FirstName,
                    LastName = c.LastName
                }).SingleOrDefaultAsync(c => c.Id == id);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditViewModel viewModel)
        {
            var customer = await _context.Customers.SingleOrDefaultAsync(c => c.Id == id);
            customer.FirstName = viewModel.FirstName;
            customer.LastName = viewModel.LastName;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet("api/customers/{id:int}/orders")]
        public async Task<IActionResult> GetOrders(int id)
        {
            var customer = await _context.Customers.SingleOrDefaultAsync(c => c.Id == id);
            if (customer == null)
                return NotFound();

            var orders = await _context.Orders.Select(o => new OrderViewModel
            {
                Date = o.OrderDate,
                Id = o.Id,
                Total = o.LineItems.Sum(l => l.Quantity * l.Product.Price)
            }).ToArrayAsync();
            return Ok(orders);
        }
    }
}

dotnet/admin-dashboard/Admin.Web/Controllers/OrdersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Admin.Web.Models;
using Admin.Web.ViewModels.Orders;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Admin.Web.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly AdminContext _context;

        public OrdersController(AdminContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var orders = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.LineItems)
                .ThenInclude(l => l.Product)
                .ToArrayAsync();
            return View(new IndexViewModel
            {
                Orders = orders,
            });
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View(new CreateViewModel
            {
                Customers = await _context.Customers.ToArrayAsync()
            });
        }

        [HttpPost("api/orders")]
        public async Task<IActionResult> CreateOrder([FromBody] ApiCreateViewModel viewModel)
        {
            var customer = await _context.Customers.SingleOrDefaultAsync(c => c.Id == viewModel.CustomerId);
            var products = await _context.Products
                .Where(p => viewModel.Items.Any(i => i.ProductId == p.Id))
                .ToArrayAsync();

            _context.Add(new Order
            {
                OrderDate = DateTime.UtcNow,
                Customer = customer,
                LineItems = products.Select(p => new OrderLineItem
                {
                    Product = p,
                    Quantity = viewModel.Items.First(i => i.ProductId == p.Id).Quantity
                }).ToArray()
            });
            await _context.SaveChangesAsync();
            return Ok();
        }
    }
}

dotnet/admin-dashboard/Admin.Web/Controllers/ProductsController.cs
using System.Threading.Tasks;
using Admin.Web.Models;
using Admin.Web.ViewModels.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Admin.Web.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly AdminContext _context;

        public ProductsController(AdminContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _context.Products.ToArrayAsync();
            return View(new IndexViewModel
            {
                Products = products
            });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateViewModel viewModel)
        {
            _context.Add(new Product
            {
                Cost = viewModel.Cost,
                Name = viewModel.Name,
                Price = viewModel.Price
            });
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(p => p.Id == id);
            return View(new EditViewModel
            {
                Id = product.Id,
                Name = product.Name,
                Cost = product.Cost,
                Price = product.Price
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditViewModel viewModel)
        {
            var product = await _context.Products.SingleOrDefaultAsync(p => p.Id == id);
            product.Name = viewModel.Name;
            product.Cost = viewModel.Cost;
            product.Price = viewModel.Price;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        
        [HttpGet("api/products")]
        public async Task<IActionResult> GetAll()
        {
            var products = await _context.Products.ToArrayAsync();
            return Ok(products);
        }

        [HttpGet("api/products/{id:int}")]
        public async Task<IActionResult> GetById(int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(p => p.Id == id);
            return Ok(product);
        } 
    }
}

dotnet/admin-dashboard/Admin.Web/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Admin.Web.Models;
using Admin.Web.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Admin.Web.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly AdminContext _context;

        public UsersController(AdminContext context)
        {
            _context = context;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var viewModel = new IndexViewModel
            {
                Users = await _context.Users.ToArrayAsync()
            };
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await _context.Users
                .Select(u => new EditViewModel
                {
                    FirstName = u.FirstName,
                    Id = u.Id,
                    LastName = u.LastName,
                    IsAdmin = u.IsAdmin
                })
                .SingleOrDefaultAsync(u => u.Id == id);
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditViewModel viewModel)
        {
            var user = await _context.Users.SingleOrDefaultAsync(u => u.Id == id);
            user.FirstName = viewModel.FirstName;
            user.LastName = viewModel.LastName;
            user.IsAdmin = viewModel.IsAdmin;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

dotnet/admin-dashboard/Admin.Web/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h5>BootXP Users Admin Dashboard</h5>
            </div>
        </div>
    </div>
</footer>

dotnet/admin-dashboard/Admin.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/styles/bootstrap.min.css" />
    <link rel="stylesheet" href="~/styles/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="~/styles/select2.min.css" />
    <link rel="stylesheet" href="~/styles/styles.css" />
    <title>@(string.IsNullOrEmpty(ViewBag.Title) ? "" : ViewBag.Title + " : " )Users Admin Dashboard</title>
</head>
<body>
@await Html.PartialAsync("_Navbar")
<div class="container">
    @RenderBody()
</div>
@await Html.PartialAsync("_Footer")
<script src="~/scripts/jquery.min.js" type="text/javascript"></script>
<script src="~/scripts/bootstrap.min.js" type="text/javascript"></script>
<script src="~/scripts/mustache.min.js" type="text/javascript"></script>
<script src="~/scripts/select2.full.min.js" type="text/javascript"></script>
<script src="~/scripts/index.js" type="text/javascript"></script>
@await RenderSectionAsync("scripts", false)

</body>
</html>

dotnet/admin-dashboard/Admin.Web/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-default">
    <div class="conatiner-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-items" aria-expanded="False">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Admin</a>
        </div>
        
        <div class="collapse navbar-collapse" id="navbar-items">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Users")">Users</a></li>
                <li><a href="@Url.Action("Index", "Customers")">Customers</a></li>
                <li><a href="@Url.Action("Index", "Orders")">Orders</a></li>
                <li><a href="@Url.Action("Index", "Products")">Products</a></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                <li><a href="@Url.Action("Register", "Account")">Register</a></li>
            </ul>
        </div>
       
    </div>
</nav>